### ISSUE TITLE
wasmate is sad with the LLVM tests

### ISSUE THREAD

**Issue by jfbastien** [WebAssembly/experimental#7]
Recording the failure I'm currently running into:
```
mkdir llvm-tests
find ./llvm/test/CodeGen/WebAssembly/ -name "*.ll" | sed 's|.*/\([^/]*\).ll|\1|g' | xargs -n1 -I{} --verbose ./out/bin/llc --mtriple=wasm32-unknown-unknown ./llvm/test/CodeGen/WebAssembly/{}.ll -o ./llvm-tests/{}.wack
find ./llvm-tests/ -name "*.wack" | sed 's|.*/\([^/]*\).wack|\1|g' | xargs -n1 -I{} --verbose ./experimental/prototype-wasmate/wasmate.py ./llvm-tests/{}.wack > ./llvm-tests/{}.wast
```
Generates:
```
Traceback (most recent call last):
  File "./experimental/prototype-wasmate/wasmate.py", line 266, in <module>
    handle_mnemonic(command, args)
  File "./experimental/prototype-wasmate/wasmate.py", line 200, in handle_mnemonic
    assert len(expr_stack) == 0
AssertionError
```

**Comment by dschuff** [comment]
#19 may be a fix for this particular error.

**Comment by binji** [comment]
Yeah, I believe all of these are fixed currently. Please reopen if not.
